### PR TITLE
Improved install guide for those using secure boot

### PR DESCRIPTION
**Pull request by mikethebos**
Great workaround for my T14s AMD Gen 1. Thanks!

This pull request integrates the modification into DKMS. This provides two advantages:
1)  Auto install on kernel updates
2)  Works on systems with Secure Boot enabled.

### CODE REVIEW

**Comment by dkebler** [comment]
In focal 20.04 ubuntu there is no unbuild command for dkms so this way fails cause the build command keeps saying that it is already built.   I tried remove, also --force --force-verison-override flags but was not allowed to build.  I can't get this method to work for me even though it would be preferable.

That dkms version is  2.8.1

You should keep a copy of the old instructions in readme for this case with a reminder that it must be done for each kennel update.

**Comment by mikethebos** [comment]
> In focal 20.04 ubuntu there is no unbuild command for dkms so this way fails cause the build command keeps saying that it is already built. I tried remove, also --force --force-verison-override flags but was not allowed to build. I can't get this method to work for me even though it would be preferable.
> 
> That dkms version is 2.8.1
> 
> You should keep a copy of the old instructions in readme for this case with a reminder that it must be done for each kennel update.

@dkebler Does running `sudo rm -rf /var/lib/dkms/<module>/<module-version>/build/` instead of unbuild help?

**Comment by mikethebos** [comment]
`sudo dkms remove ...` might work, too.

**Comment by dkebler** [comment]
(is there a way to set an issue on your fork instead of using this pr?  github is not offering such)

I loaded this current version of dkms that has unbuild
https://github.com/dell/dkms

I had your branch working fine then my kernel was updated to Linux 5.4.0-89-generic (ubuntu focal) and now the evdi module issue is back.

But sadly after trying to rebuild/make the module (and using dkms instead) the issue is not resolved  

not sure if it is the module is not longer working with the new kernel or I am just not getting the build in place correctly.  Any way to tell?

BTW I wrote a script to automate this (not perfect).  Can you tell from output (below).  Note it installs to /updates/dkms  why not 
to /kernal/drivers/gpu/drm/evdi  like the manual copy?  These two are not the same modified date/size   

```
#!/bin/bash
echo "**** this script must be run from the parent of the the evdi repo ****"
ls -la /usr/src | grep evdi
echo enter the latest evdi driver version
read version
echo "***** moving /usr/src/evdi-$version to evdi-$version.original ****"
sudo mv /usr/src/evdi-$version evdi-$version.original
sudo chmod -R 0444 evdi-$version.original
echo "***** copying sudo evdi/module to /usr/src/evdi-$version ****"
sudo cp -R evdi/module /usr/src/evdi-$version
echo "**** uninstalling module evdi version $version ****"
sudo dkms uninstall evdi/$version
echo "**** unbuilding module evdi version $version ****"
sudo dkms unbuild evdi/$version
echo "**** building module evdi version $version *****"
sudo dkms build evdi/$version
echo "**** installing module evdi version $version ****"
sudo dkms install evdi/$version

LINE="vmap_texture=1"
FILE="/etc/modprobe.d/evdi.conf"
grep -qxF "$LINE" "$FILE" || echo "$LINE" | sudo tee --append "$FILE"
echo "**** appended $LINE to $FILE ****"
cat $FILE
```

and here is the output
```
***** copying sudo evdi/module to /usr/src/evdi-1.9.1 ****
**** uninstalling module evdi version 1.9.1 ****
Module evdi-1.9.1 for kernel 5.4.0-89-generic (x86_64).
Before uninstall, this module version was ACTIVE on this kernel.

evdi.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.4.0-89-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.
depmod....
**** unbuilding module evdi version 1.9.1 ****
Module evdi 1.9.1 is not installed for kernel 5.4.0-89-generic (x86_64). Skipping...
**** building module evdi version 1.9.1 *****

Building module:
cleaning build area...
make -j8 KERNELRELEASE=5.4.0-89-generic all INCLUDEDIR=/lib/modules/5.4.0-89-generic/build/include KVERSION=5.4.0-89-generic DKMS_BUILD=1....
cleaning build area...
**** installing module evdi version 1.9.1 ****

evdi.ko:
Running module version sanity check.
 - Original module
 - Installation
   - Installing to /lib/modules/5.4.0-89-generic/updates/dkms/
depmod...
**** appended vmap_texture=1 to /etc/modprobe.d/evdi.conf ****
options evdi initial_device_count=4
vmap_texture=1
```

**Comment by dkebler** [comment]
dkms status shows

```
evdi/1.7.2, 5.4.0-80-generic, x86_64: built
evdi/1.7.2, 5.4.0-84-generic, x86_64: built
evdi/1.7.2, 5.4.0-86-generic, x86_64: built
evdi/1.7.2, 5.4.0-88-generic, x86_64: installed (WARNING! Diff between built and installed module!)
evdi/1.7.2, 5.4.0-89-generic, x86_64: built
evdi/1.9.1, 5.4.0-88-generic, x86_64: built
evdi/1.9.1, 5.4.0-89-generic, x86_64: installedError! Could not locate dkms.conf file.
File: /var/lib/dkms/original/evdi-1.9.1/source/dkms.conf does not exist.
```

hmmm...how do I fix this?

**Comment by dkebler** [comment]
ok that was a bad link now I get the Diff error 

evdi/1.9.1, 5.4.0-89-generic, x86_64: installed
original/evdi-1.9.1, 5.4.0-88-generic, x86_64: installed (original_module exists) (WARNING! Diff between built and installed module!)
original/evdi-1.9.1, 5.4.0-89-generic, x86_64: installed (WARNING! Diff between built and installed module!)

I'll keep fiddling,  and repot back

**Comment by mikethebos** [comment]
I think you need to uninstall the 1.7.2 version. Also, make sure to uninstall the original version before moving it to a backup dir.

**Comment by mikethebos** [comment]
You may want to make your backup dirs somewhere else,

**Comment by dkebler** [comment]
Ok It's all good.  That diff refered to the original which is different.  The dkms build/install worked.   

Final issue was that the script I wrote appended the vmap_texture=1 on a new line instead of same.  Running `displaylink` at the cli showed error in that file.  Once I fixed it the module loaded and all is good!!

So am I correct that now with dkms install your fork of module should be (brought forward/built) with each new kernel update?

**Comment by mikethebos** [comment]
Yes. Assuming the fork's module dir is now in /usr/src/... 

Should we update the README? If so, how do you propose we change it? Ideally, it should still use DKMS, but avoid the unbuild option... Thus, I'm curious if `sudo dkms remove` or `sudo rm -rf /var/lib/dkms/<module>/<module-version>/build/` works in place of unbuild.

**Comment by dkebler** [comment]
fixed

```
[[ $(cat $FILE | grep $LINE) ]] && exit 0
sudo sed -i "s/$/$LINE/" "$FILE"
echo "**** appended $LINE to $FILE ****"
cat $FILE
```

I made a gist of install script you may want to link on the readmin.  
Thanks for your fork!!  without it my new ryzen box with displaylink was a brick.
https://gist.github.com/dkebler/0d10d599fcde9dceaef9a3ccfa39a9f3#file-evdi-install-sh

**Comment by mikethebos** [comment]
Thanks go to @pioto1225

**Comment by dkebler** [comment]
Yea I don't know about how to get the dkms to work with old version that had no unbuild.  As I mentioned I tried remove, force etc.   I suggest just including a link to that dkms repo for latest version.  It was easy enough to install on ubuntu.  Then new directions worked as written.

https://github.com/dell/dkms

**Pull request merged**
